language: python

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -yn dqn python=3 tensorflow tensorflow-gpu opencv psutil
  - source activate dqn
  - pip install gym[atari]
  - git clone https://github.com/AdamStelmaszczyk/dqn.git

script:
  - cd dqn
  - python run.py --test
