language: python

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -n dqn python=3.5.2
  - source activate dqn
  - git clone https://github.com/AdamStelmaszczyk/dqn.git
  - pip install -r requirements.txt

script:
  - cd dqn
  - neptune run --offline -- --test True
